// src/data.js
export const foodData = [
  // Indian Veg
  {
    id: 1,
    name: 'Mushroom Masala',
    category: 'Indian Veg',
    price: '₹120',
    image: 'https://palatesdesire.com/wp-content/uploads/2022/09/mushroom-masala-recipe@palates-desire.jpg',
  },
  {
    id: 2,
    name: 'Mushroom Butter Masala',
    category: 'Indian Veg',
    price: '₹130',
    image: 'https://dhaba-sardardaa.com/wp-content/uploads/2021/12/mushroom-masala.jpg',
  },
  {
    id: 3,
    name: 'Panner Masala',
    category: 'Indian Veg',
    price: '₹120',
    image: 'https://www.whiskaffair.com/wp-content/uploads/2020/08/Dhaba-Style-Paneer-Masala-2-3.jpg',
  },
  {
    id: 4,
    name: 'Panner Punjabi',
    category: 'Indian Veg',
    price: '₹140',
    image: 'https://honestcooking.com/wp-content/uploads/2012/09/Paneer-Masala-Recipe.jpg',
  },
  {
    id: 5,
    name: 'Panner Butter Masala',
    category: 'Indian Veg',
    price: '₹130',
    image: 'https://fforflavour.com/wp-content/uploads/2018/08/IMG_5518.jpg',
  },
  {
    id: 6,
    name: 'Kobi Masala',
    category: 'Indian Veg',
    price: '₹120',
    image: 'https://www.indianhealthyrecipes.com/wp-content/uploads/2024/04/gobi-masala-cauliflower-masala-recipe.webp',
  },
  // Indian Non-veg
  {
    id: 7,
    name: 'Chicken Masala',
    category: 'Indian Non Veg',
    price: '₹120',
    image: 'https://www.whiskaffair.com/wp-content/uploads/2021/01/Chicken-Masala-2-3-1.jpg',
  },
  {
    id: 8,
    name: 'Chicken Butter Masala',
    category: 'Indian Non Veg',
    price: '₹140',
    image: 'https://images.immediate.co.uk/production/volatile/sites/30/2021/02/butter-chicken-ac2ff98.jpg?quality=90&resize=440,400',
  },
  {
    id: 9,
    name: 'Chicken Punjabi',
    category: 'Indian Non Veg',
    price: '₹140',
    image: 'https://onestophalal.com/cdn/shop/articles/punjabi_chicken_curry-1699075119880_1200x.jpg?v=1699075165',
  },
  {
    id: 10,
    name: 'Chicken Kadai',
    category: 'Indian Non Veg',
    price: '₹130',
    image: 'https://static.toiimg.com/thumb/53523514.cms?imgsize=102389&width=800&height=800',
  },
  {
    id: 11,
    name: 'Chicken Hydrabadi',
    category: 'Indian Non Veg',
    price: '₹140',
    image: 'https://theyummydelights.com/wp-content/uploads/2019/07/hyderabadi-chicken-masala-9.jpg',
  },
  {
    id: 12,
    name: 'Garlic Chicken',
    category: 'Indian Non Veg',
    price: '₹130',
    image: 'https://www.thespruceeats.com/thmb/tGcR66jMgCb0KUbl-zus8GjKeN0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/instant-pot-honey-garlic-chicken-recipe-5204292-hero-01-108a039fdc644a1ca26df9e0c170dac4.jpg',
  },
  {
    id: 13,
    name: 'Ginger Chicken',
    category: 'Indian Non Veg',
    price: '₹130',
    image: 'https://christieathome.com/wp-content/uploads/2023/06/Ginger-Chicken-16-1.jpg',
  },
  {
    id: 14,
    name: 'Chicken Mughlai',
    category: 'Indian Non Veg',
    price: '₹130',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXt6hf6t_sE2H3Yo1SW9hNskxJ7Cl2qj3N5A&s',
  },
  {
    id: 15,
    name: 'Chicken Dopiaza',
    category: 'Indian Non Veg',
    price: '₹150',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ1komEoBwo4fuWwWHCwhGG_fPn-p1Yjv_U5Q&s',
  },
  {
    id: 16,
    name: 'Rice Chicken',
    category: 'Indian Non Veg',
    price: '₹130',
    image: 'https://static.vecteezy.com/system/resources/thumbnails/023/830/963/small/mixed-rice-with-chicken-slice-ai-generate-photo.jpg',
  },
];
